name = "Kiera"
license = "MIT"
description = "Hugo Theme for creative and technical writing"
tags = ["blog","minimal","responsive"]
features = ["blog","disqus","google-analytics","font-awesome"]
min_version = "0.55.0"

[author]
  name = "Melany Cordoba"
  homepage = "https://github.com/MelaCordoba/tarea1Mel.git"


 
